version: '3.8'

services:
  app:
    build: .  # Directory containing Dockerfile for Go app
    ports:
      - "8080:8080"  # Map port 8080 on the host to port 8080 in the container
    depends_on:
      - db  # Ensures db starts first
    # entrypoint: /wait-for-it.sh db:5432 --timeout=30 -- ./main
    environment:
      DATABASE_URL: postgresql://root:password@db:5432/tax_assessment?sslmode=disable  # Use service name 'db' as host
      

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "25432:5432"  
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  postgres_data:
