version: '3'

services:
    postgres:
        image: postgres:16.0
        environment:
            POSTGRES_DB: test_db
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
        
        ports:
            - "15432:5432"

volumes:
    pgdata: